version: "3"
services:
  admin_system:
    image: bhmall-admin-system:0.0.1
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
     - bhmall-admin-overlay
    ports:
     - "8775:8775"
    environment:
     - HOST=Aserver
     - PROFILE=swarm     
     - MYSQL=bhmall-mysql
     - REDIS=bhmall-redis


networks:
  bhmall-admin-overlay:
    external:
      name: bhmall-admin-overlay
