version: "3"
services:
  admin_config:
    image: bhmall-admin-config:0.0.1	
    deploy:
      replicas: 2
    ports:
     - "8762:8762"
    networks:
     -  bhmall-overlay
    environment:
     - HOST=Aserver
     - PROFILE=swarm

networks:
  bhmall-overlay:
    external:
      name: bhmall-overlay
