version: "3"
services:
  admin_server:
    image: bhmall-admin-server:0.0.1 
    deploy:
      replicas: 2
    networks:
      bhmall-overlay:
        aliases:
          - Aserver
    ports:
     - "8761:8761"
    environment:
     - HOST=Aserver
     - PROFILE=swarm

networks:
  bhmall-overlay:
    external:
      name: bhmall-overlay
