version: "3"
services:
  nginx:
    image: nginx
    networks:
     - bhmall-overlay
    ports:
     - "80:80"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/html:/usr/share/nginx/html
    container_name: nginx

networks:
  bhmall-overlay:
    external:
      name: bhmall-overlay
