version: "2"
services:
  bhmall-mem-cms:
    image: bhmall-mem-cms:0.0.1
    restart: always
    container_name: bhmall-mem-cms
    network_mode: host
    environment:
     - SERVER_PORT=-Dserver.port=8765
     - PROFILE=--spring.cloud.config.profile=test
