server:
  port: 8762
spring:
  application:
    name: admin-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90