version: "3"  
services:
  micro-cloud-admin-server:
    image: micro-cloud-admin-server:0.0.1
   # 到阿里云拉镜像 registry.cn-shenzhen.aliyuncs.com/zhangzhicheng/zhangzhicheng:micro-cloud-admin-server-0.0.1
   # container_name: micro-cloud-admin-server 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - admin-server
    ports:
     - 8761:8761
    environment:
     - PROFILE=dev
     - HOST=admin-server
     
  micro-cloud-admin-config:
    image: micro-cloud-admin-config:0.0.1
    # 到阿里云拉镜像 registry.cn-shenzhen.aliyuncs.com/zhangzhicheng/zhangzhicheng:micro-cloud-admin-config-0.0.1
    #container_name: micro-cloud-admin-config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - admin-config
    ports:
     - 8762:8762
    environment:
     - PROFILE=dev
     - HOST=admin-server
    
  micro-cloud-admin-zuul:
    image: micro-cloud-admin-zuul:0.0.1
    #container_name: micro-cloud-admin-zuul
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - gateway-service-zuul 
    ports:
     - 8760:8760
    environment:
     - PROFILE=dev
     - HOST=admin-server

        
networks:
  cloudsystem-overlay:
    external:
      name: cloudsystem-overlay