version: "3" 
services:
  micro-cloud-admin-goods:
    image: micro-cloud-admin-goods:0.0.1
    # 去阿里云拉镜像 registry.cn-shenzhen.aliyuncs.com/zhangzhicheng/zhangzhicheng:micro-cloud-admin-goods-0.0.1
    #container_name: micro-cloud-admin-goods
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - goods-service
    ports:
     - 8767:8767
    environment:
     - PROFILE=dev
     - HOST=adminserver
     - CONFIG=adminconfig
 
networks:
  cloudsystem-overlay:
    external:
      name: cloudsystem-overlay