version: "3"  
services:
  micro-cloud-admin-server:
    image: micro-cloud-admin-server:0.0.1
   # 到阿里云拉镜像 registry.cn-shenzhen.aliyuncs.com/zhangzhicheng/zhangzhicheng:micro-cloud-adminserver-0.0.1
   # container_name: micro-cloud-adminserver 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - adminserver
    ports:
     - 8761:8761
    environment:
     - PROFILE=dev
     - HOST=adminserver
     - eureka.environment=dev
     
  micro-cloud-admin-config:
    image: micro-cloud-admin-config:0.0.1
    # 到阿里云拉镜像 registry.cn-shenzhen.aliyuncs.com/zhangzhicheng/zhangzhicheng:micro-cloud-admin-config-0.0.1
    #container_name: micro-cloud-admin-config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - adminconfig
    ports:
     - 8762:8762
    environment:
     - PROFILE=dev
     - HOST=adminserver
     - TXHOST=admintx
    
  micro-cloud-admin-zuul:
    image: micro-cloud-admin-zuul:0.0.1
    #container_name: micro-cloud-admin-zuul
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - zuul 
    ports:
     - 8760:8760
    environment:
     - PROFILE=dev
     - HOST=adminserver
     - zuul.routes.system-service.url=http://system-service:8765/
     - zuul.routes.security-service.url=http://security-service:8769/
     - zuul.routes.goods-service.url=http://goods-service:8765/
     - zuul.routes.member-service.url=http://member-service:8773/
        
networks: 
  cloudsystem-overlay:
    external:
      name: cloudsystem-overlay