version: "3" 
services:
  micro-cloud-admin-member:
    image: micro-cloud-admin-member:0.0.1
    # 去阿里云拉镜像 registry.cn-shenzhen.aliyuncs.com/zhangzhicheng/zhangzhicheng:micro-cloud-admin-member-0.0.1
    #container_name: micro-cloud-admin-member
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      cloudsystem-overlay:
        aliases:
          - adminmember
    ports:
     - 8773:8773
    environment:
     - PROFILE=dev
     - HOST=adminserver
     - CONFIG=adminconfig
 
networks:
  cloudsystem-overlay:
    external:
      name: cloudsystem-overlay