server:
  port: 8760
spring:
  application:
    name: gateway-service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 60
    lease-expiration-duration-in-seconds: 120   


    
zuul:
    sensitive-headers: null
    host:
        connect-timeout-millis: 60000
        socket-timeout-millis:  60000
    retryable: true
    routes:
        system-service:
            path: /system-service/**
            url: http://system-service:8765/
            sensitive-headers:
        security-service:
            path: /security-service/**
            url: http://security-service:8769/
            sensitive-headers:
        goods-service:
            path: /goods-service/**
            url: http://goods-service:8765/ 
            sensitive-headers:
        member-service:
            path: /member-service/**
            url: http://member-service:8767/
            sensitive-headers:
            
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
          
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000 